import {
  AuthCommandCenterApproveScope,
  AuthCommandCenterOperateScope,
  AuthCommandCenterReadScope,
  COMMAND_CENTER_WS_METHODS,
  type AuthEnvironmentScope,
} from "@t3tools/contracts";

export const COMMAND_CENTER_RPC_SCOPE_ENTRIES = [
  [COMMAND_CENTER_WS_METHODS.bootstrap, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.commandSubmit, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.runStart, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.eventsReplay, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.eventsSubscribe, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.timelineQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.spacesQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.spacesSync, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.itemsQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.inboxQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.inboxDetail, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.inboxComment, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxRequestChanges, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxCandidateCreate, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxCandidateAccept, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxCandidateDiscard, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxChangeRequestResolve, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxSnooze, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxUnsnooze, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxDismiss, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.inboxReopen, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.sprintPlanList, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.sprintPlanPreviewImport, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.sprintPlanApplyImport, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.sprintPlanGetCurrent, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.sprintPlanGetOriginal, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.sprintPlanPatchTask, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.sprintPlanResolveDateConflict, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.sprintPlanListHistory, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.itemUpdate, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.runsQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.automationsQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.automationDefinitionGet, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.automationDefinitionCreate, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.automationDefinitionSave, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.automationScheduleInterpret, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.approvalsQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.artifactsQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.connectionsQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.connectionsRefresh, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.googleConnectionSetupBegin, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.googleConnectionSetupComplete, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.googleConnectionRemove, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.memoryQuery, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.memorySearch, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.itemCreate, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.memoryRemember, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.memoryPropose, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.memoryReview, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.approvalDecide, AuthCommandCenterApproveScope],
  [COMMAND_CENTER_WS_METHODS.automationRunStart, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.automationRunGet, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.automationWebhookAdmit, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.googleRead, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.observationsList, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.observationsGet, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.observationsHistory, AuthCommandCenterReadScope],
  [COMMAND_CENTER_WS_METHODS.observationsCreateManual, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.observationsImport, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.observationsCorrect, AuthCommandCenterOperateScope],
  [COMMAND_CENTER_WS_METHODS.observationsRetire, AuthCommandCenterOperateScope],
] as const satisfies ReadonlyArray<readonly [string, AuthEnvironmentScope]>;

const COMMAND_CENTER_RPC_METHODS = new Set<string>(
  COMMAND_CENTER_RPC_SCOPE_ENTRIES.map(([method]) => method),
);

/** Every Command Center RPC is gated because even its current read paths may
 * refresh private-config projections or rebuild local indexes. */
export const commandCenterRpcRequiresReadiness = (method: string): boolean =>
  COMMAND_CENTER_RPC_METHODS.has(method);
